// Map post slugs → CDN-hosted OG/Twitter preview image URLs.
// Images are generated by /tmp/genog.py and uploaded via lovable-assets.
import agentic from "@/assets/og/og-blog-agentic-ai-enterprise-automation.png.asset.json";
import rag from "@/assets/og/og-blog-scalable-rag-enterprise.png.asset.json";
import saas from "@/assets/og/og-blog-cloud-native-saas-patterns.png.asset.json";
import leadership from "@/assets/og/og-blog-engineering-leadership-global-teams.png.asset.json";
import delivery from "@/assets/og/og-blog-ai-delivery-predictability.png.asset.json";
import payments from "@/assets/og/og-blog-payments-platform-modernization.png.asset.json";
import dataBI from "@/assets/og/og-blog-data-platform-bi-at-scale.png.asset.json";
import projectsOg from "@/assets/og/og-projects.png.asset.json";
import caseStudiesOg from "@/assets/og/og-case-studies.png.asset.json";
import researchOg from "@/assets/og/og-research.png.asset.json";
import learnOg from "@/assets/og/og-learn.png";
import newsletterOg from "@/assets/og/og-newsletter.png";

export const SITE_ORIGIN = "https://www.dibyamishra.co.in";

const abs = (u: string) => (u.startsWith("http") ? u : `${SITE_ORIGIN}${u}`);

export const postOgImages: Record<string, string> = {
  "agentic-ai-enterprise-automation": abs(agentic.url),
  "scalable-rag-enterprise": abs(rag.url),
  "cloud-native-saas-patterns": abs(saas.url),
  "engineering-leadership-global-teams": abs(leadership.url),
  "ai-delivery-predictability": abs(delivery.url),
  "payments-platform-modernization": abs(payments.url),
  "data-platform-bi-at-scale": abs(dataBI.url),
};

export const pageOgImages = {
  projects: abs(projectsOg.url),
  caseStudies: abs(caseStudiesOg.url),
  research: abs(researchOg.url),
  blog: abs(researchOg.url),
  learn: abs(learnOg),
  newsletter: abs(newsletterOg),
};

