/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AtomDotxmlRouteImport } from './routes/atom[.]xml'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsletterIndexRouteImport } from './routes/newsletter.index'
import { Route as WhitePaperAgenticAiEnterpriseAutomationRouteImport } from './routes/white-paper.agentic-ai-enterprise-automation'
import { Route as NewsletterSlugRouteImport } from './routes/newsletter.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedRepositoryRouteImport } from './routes/_authenticated/repository'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicTtsRouteImport } from './routes/api/public/tts'
import { Route as ApiPublicTrackVisitRouteImport } from './routes/api/public/track-visit'
import { Route as ApiPublicNewsletterRouteImport } from './routes/api/public/newsletter'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiPublicChatRouteImport } from './routes/api/public/chat'
import { Route as ApiDownloadPdfRouteImport } from './routes/api/download.pdf'
import { Route as AuthenticatedAdminVisitorAuditRouteImport } from './routes/_authenticated/admin/visitor-audit'
import { Route as AuthenticatedAdminSpamAuditRouteImport } from './routes/_authenticated/admin/spam-audit'
import { Route as AuthenticatedAdminSecurityEventsRouteImport } from './routes/_authenticated/admin/security-events'
import { Route as AuthenticatedAdminBlockedDomainsRouteImport } from './routes/_authenticated/admin/blocked-domains'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicCronNewsletterSchedulerRouteImport } from './routes/api/public/cron/newsletter-scheduler'
import { Route as ApiPublicCronMonthlyNewsletterRouteImport } from './routes/api/public/cron/monthly-newsletter'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AtomDotxmlRoute = AtomDotxmlRouteImport.update({
  id: '/atom.xml',
  path: '/atom.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterIndexRoute = NewsletterIndexRouteImport.update({
  id: '/newsletter/',
  path: '/newsletter/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhitePaperAgenticAiEnterpriseAutomationRoute =
  WhitePaperAgenticAiEnterpriseAutomationRouteImport.update({
    id: '/white-paper/agentic-ai-enterprise-automation',
    path: '/white-paper/agentic-ai-enterprise-automation',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewsletterSlugRoute = NewsletterSlugRouteImport.update({
  id: '/newsletter/$slug',
  path: '/newsletter/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedRepositoryRoute = AuthenticatedRepositoryRouteImport.update({
  id: '/repository',
  path: '/repository',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTtsRoute = ApiPublicTtsRouteImport.update({
  id: '/api/public/tts',
  path: '/api/public/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackVisitRoute = ApiPublicTrackVisitRouteImport.update({
  id: '/api/public/track-visit',
  path: '/api/public/track-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNewsletterRoute = ApiPublicNewsletterRouteImport.update({
  id: '/api/public/newsletter',
  path: '/api/public/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadPdfRoute = ApiDownloadPdfRouteImport.update({
  id: '/api/download/pdf',
  path: '/api/download/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminVisitorAuditRoute =
  AuthenticatedAdminVisitorAuditRouteImport.update({
    id: '/admin/visitor-audit',
    path: '/admin/visitor-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSpamAuditRoute =
  AuthenticatedAdminSpamAuditRouteImport.update({
    id: '/admin/spam-audit',
    path: '/admin/spam-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSecurityEventsRoute =
  AuthenticatedAdminSecurityEventsRouteImport.update({
    id: '/admin/security-events',
    path: '/admin/security-events',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBlockedDomainsRoute =
  AuthenticatedAdminBlockedDomainsRouteImport.update({
    id: '/admin/blocked-domains',
    path: '/admin/blocked-domains',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronNewsletterSchedulerRoute =
  ApiPublicCronNewsletterSchedulerRouteImport.update({
    id: '/api/public/cron/newsletter-scheduler',
    path: '/api/public/cron/newsletter-scheduler',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronMonthlyNewsletterRoute =
  ApiPublicCronMonthlyNewsletterRouteImport.update({
    id: '/api/public/cron/monthly-newsletter',
    path: '/api/public/cron/monthly-newsletter',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atom.xml': typeof AtomDotxmlRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/learn': typeof LearnRoute
  '/mcp': typeof McpRoute
  '/projects': typeof ProjectsRoute
  '/research': typeof ResearchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/repository': typeof AuthenticatedRepositoryRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/newsletter/$slug': typeof NewsletterSlugRoute
  '/white-paper/agentic-ai-enterprise-automation': typeof WhitePaperAgenticAiEnterpriseAutomationRoute
  '/newsletter/': typeof NewsletterIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/blocked-domains': typeof AuthenticatedAdminBlockedDomainsRoute
  '/admin/security-events': typeof AuthenticatedAdminSecurityEventsRoute
  '/admin/spam-audit': typeof AuthenticatedAdminSpamAuditRoute
  '/admin/visitor-audit': typeof AuthenticatedAdminVisitorAuditRoute
  '/api/download/pdf': typeof ApiDownloadPdfRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRoute
  '/api/public/track-visit': typeof ApiPublicTrackVisitRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/cron/monthly-newsletter': typeof ApiPublicCronMonthlyNewsletterRoute
  '/api/public/cron/newsletter-scheduler': typeof ApiPublicCronNewsletterSchedulerRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atom.xml': typeof AtomDotxmlRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/learn': typeof LearnRoute
  '/mcp': typeof McpRoute
  '/projects': typeof ProjectsRoute
  '/research': typeof ResearchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/repository': typeof AuthenticatedRepositoryRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/newsletter/$slug': typeof NewsletterSlugRoute
  '/white-paper/agentic-ai-enterprise-automation': typeof WhitePaperAgenticAiEnterpriseAutomationRoute
  '/newsletter': typeof NewsletterIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/blocked-domains': typeof AuthenticatedAdminBlockedDomainsRoute
  '/admin/security-events': typeof AuthenticatedAdminSecurityEventsRoute
  '/admin/spam-audit': typeof AuthenticatedAdminSpamAuditRoute
  '/admin/visitor-audit': typeof AuthenticatedAdminVisitorAuditRoute
  '/api/download/pdf': typeof ApiDownloadPdfRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRoute
  '/api/public/track-visit': typeof ApiPublicTrackVisitRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/cron/monthly-newsletter': typeof ApiPublicCronMonthlyNewsletterRoute
  '/api/public/cron/newsletter-scheduler': typeof ApiPublicCronNewsletterSchedulerRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/atom.xml': typeof AtomDotxmlRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/learn': typeof LearnRoute
  '/mcp': typeof McpRoute
  '/projects': typeof ProjectsRoute
  '/research': typeof ResearchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/repository': typeof AuthenticatedRepositoryRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/newsletter/$slug': typeof NewsletterSlugRoute
  '/white-paper/agentic-ai-enterprise-automation': typeof WhitePaperAgenticAiEnterpriseAutomationRoute
  '/newsletter/': typeof NewsletterIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/blocked-domains': typeof AuthenticatedAdminBlockedDomainsRoute
  '/_authenticated/admin/security-events': typeof AuthenticatedAdminSecurityEventsRoute
  '/_authenticated/admin/spam-audit': typeof AuthenticatedAdminSpamAuditRoute
  '/_authenticated/admin/visitor-audit': typeof AuthenticatedAdminVisitorAuditRoute
  '/api/download/pdf': typeof ApiDownloadPdfRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRoute
  '/api/public/track-visit': typeof ApiPublicTrackVisitRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/cron/monthly-newsletter': typeof ApiPublicCronMonthlyNewsletterRoute
  '/api/public/cron/newsletter-scheduler': typeof ApiPublicCronNewsletterSchedulerRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/atom.xml'
    | '/auth'
    | '/blog'
    | '/case-studies'
    | '/contact'
    | '/forgot-password'
    | '/learn'
    | '/mcp'
    | '/projects'
    | '/research'
    | '/reset-password'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/trust'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/reports'
    | '/repository'
    | '/blog/$slug'
    | '/email/unsubscribe'
    | '/newsletter/$slug'
    | '/white-paper/agentic-ai-enterprise-automation'
    | '/newsletter/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/blocked-domains'
    | '/admin/security-events'
    | '/admin/spam-audit'
    | '/admin/visitor-audit'
    | '/api/download/pdf'
    | '/api/public/chat'
    | '/api/public/contact'
    | '/api/public/newsletter'
    | '/api/public/track-visit'
    | '/api/public/tts'
    | '/lovable/email/suppression'
    | '/api/public/cron/monthly-newsletter'
    | '/api/public/cron/newsletter-scheduler'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/atom.xml'
    | '/auth'
    | '/blog'
    | '/case-studies'
    | '/contact'
    | '/forgot-password'
    | '/learn'
    | '/mcp'
    | '/projects'
    | '/research'
    | '/reset-password'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/trust'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/reports'
    | '/repository'
    | '/blog/$slug'
    | '/email/unsubscribe'
    | '/newsletter/$slug'
    | '/white-paper/agentic-ai-enterprise-automation'
    | '/newsletter'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/blocked-domains'
    | '/admin/security-events'
    | '/admin/spam-audit'
    | '/admin/visitor-audit'
    | '/api/download/pdf'
    | '/api/public/chat'
    | '/api/public/contact'
    | '/api/public/newsletter'
    | '/api/public/track-visit'
    | '/api/public/tts'
    | '/lovable/email/suppression'
    | '/api/public/cron/monthly-newsletter'
    | '/api/public/cron/newsletter-scheduler'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/atom.xml'
    | '/auth'
    | '/blog'
    | '/case-studies'
    | '/contact'
    | '/forgot-password'
    | '/learn'
    | '/mcp'
    | '/projects'
    | '/research'
    | '/reset-password'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/trust'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/reports'
    | '/_authenticated/repository'
    | '/blog/$slug'
    | '/email/unsubscribe'
    | '/newsletter/$slug'
    | '/white-paper/agentic-ai-enterprise-automation'
    | '/newsletter/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/blocked-domains'
    | '/_authenticated/admin/security-events'
    | '/_authenticated/admin/spam-audit'
    | '/_authenticated/admin/visitor-audit'
    | '/api/download/pdf'
    | '/api/public/chat'
    | '/api/public/contact'
    | '/api/public/newsletter'
    | '/api/public/track-visit'
    | '/api/public/tts'
    | '/lovable/email/suppression'
    | '/api/public/cron/monthly-newsletter'
    | '/api/public/cron/newsletter-scheduler'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AtomDotxmlRoute: typeof AtomDotxmlRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LearnRoute: typeof LearnRoute
  McpRoute: typeof McpRoute
  ProjectsRoute: typeof ProjectsRoute
  ResearchRoute: typeof ResearchRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrustRoute: typeof TrustRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  NewsletterSlugRoute: typeof NewsletterSlugRoute
  WhitePaperAgenticAiEnterpriseAutomationRoute: typeof WhitePaperAgenticAiEnterpriseAutomationRoute
  NewsletterIndexRoute: typeof NewsletterIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiDownloadPdfRoute: typeof ApiDownloadPdfRoute
  ApiPublicChatRoute: typeof ApiPublicChatRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicNewsletterRoute: typeof ApiPublicNewsletterRoute
  ApiPublicTrackVisitRoute: typeof ApiPublicTrackVisitRoute
  ApiPublicTtsRoute: typeof ApiPublicTtsRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicCronMonthlyNewsletterRoute: typeof ApiPublicCronMonthlyNewsletterRoute
  ApiPublicCronNewsletterSchedulerRoute: typeof ApiPublicCronNewsletterSchedulerRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atom.xml': {
      id: '/atom.xml'
      path: '/atom.xml'
      fullPath: '/atom.xml'
      preLoaderRoute: typeof AtomDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/': {
      id: '/newsletter/'
      path: '/newsletter'
      fullPath: '/newsletter/'
      preLoaderRoute: typeof NewsletterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/white-paper/agentic-ai-enterprise-automation': {
      id: '/white-paper/agentic-ai-enterprise-automation'
      path: '/white-paper/agentic-ai-enterprise-automation'
      fullPath: '/white-paper/agentic-ai-enterprise-automation'
      preLoaderRoute: typeof WhitePaperAgenticAiEnterpriseAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/$slug': {
      id: '/newsletter/$slug'
      path: '/newsletter/$slug'
      fullPath: '/newsletter/$slug'
      preLoaderRoute: typeof NewsletterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/repository': {
      id: '/_authenticated/repository'
      path: '/repository'
      fullPath: '/repository'
      preLoaderRoute: typeof AuthenticatedRepositoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tts': {
      id: '/api/public/tts'
      path: '/api/public/tts'
      fullPath: '/api/public/tts'
      preLoaderRoute: typeof ApiPublicTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track-visit': {
      id: '/api/public/track-visit'
      path: '/api/public/track-visit'
      fullPath: '/api/public/track-visit'
      preLoaderRoute: typeof ApiPublicTrackVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter': {
      id: '/api/public/newsletter'
      path: '/api/public/newsletter'
      fullPath: '/api/public/newsletter'
      preLoaderRoute: typeof ApiPublicNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download/pdf': {
      id: '/api/download/pdf'
      path: '/api/download/pdf'
      fullPath: '/api/download/pdf'
      preLoaderRoute: typeof ApiDownloadPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/visitor-audit': {
      id: '/_authenticated/admin/visitor-audit'
      path: '/admin/visitor-audit'
      fullPath: '/admin/visitor-audit'
      preLoaderRoute: typeof AuthenticatedAdminVisitorAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/spam-audit': {
      id: '/_authenticated/admin/spam-audit'
      path: '/admin/spam-audit'
      fullPath: '/admin/spam-audit'
      preLoaderRoute: typeof AuthenticatedAdminSpamAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/security-events': {
      id: '/_authenticated/admin/security-events'
      path: '/admin/security-events'
      fullPath: '/admin/security-events'
      preLoaderRoute: typeof AuthenticatedAdminSecurityEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/blocked-domains': {
      id: '/_authenticated/admin/blocked-domains'
      path: '/admin/blocked-domains'
      fullPath: '/admin/blocked-domains'
      preLoaderRoute: typeof AuthenticatedAdminBlockedDomainsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/newsletter-scheduler': {
      id: '/api/public/cron/newsletter-scheduler'
      path: '/api/public/cron/newsletter-scheduler'
      fullPath: '/api/public/cron/newsletter-scheduler'
      preLoaderRoute: typeof ApiPublicCronNewsletterSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/monthly-newsletter': {
      id: '/api/public/cron/monthly-newsletter'
      path: '/api/public/cron/monthly-newsletter'
      fullPath: '/api/public/cron/monthly-newsletter'
      preLoaderRoute: typeof ApiPublicCronMonthlyNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRepositoryRoute: typeof AuthenticatedRepositoryRoute
  AuthenticatedAdminBlockedDomainsRoute: typeof AuthenticatedAdminBlockedDomainsRoute
  AuthenticatedAdminSecurityEventsRoute: typeof AuthenticatedAdminSecurityEventsRoute
  AuthenticatedAdminSpamAuditRoute: typeof AuthenticatedAdminSpamAuditRoute
  AuthenticatedAdminVisitorAuditRoute: typeof AuthenticatedAdminVisitorAuditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRepositoryRoute: AuthenticatedRepositoryRoute,
  AuthenticatedAdminBlockedDomainsRoute: AuthenticatedAdminBlockedDomainsRoute,
  AuthenticatedAdminSecurityEventsRoute: AuthenticatedAdminSecurityEventsRoute,
  AuthenticatedAdminSpamAuditRoute: AuthenticatedAdminSpamAuditRoute,
  AuthenticatedAdminVisitorAuditRoute: AuthenticatedAdminVisitorAuditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AtomDotxmlRoute: AtomDotxmlRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LearnRoute: LearnRoute,
  McpRoute: McpRoute,
  ProjectsRoute: ProjectsRoute,
  ResearchRoute: ResearchRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrustRoute: TrustRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  NewsletterSlugRoute: NewsletterSlugRoute,
  WhitePaperAgenticAiEnterpriseAutomationRoute:
    WhitePaperAgenticAiEnterpriseAutomationRoute,
  NewsletterIndexRoute: NewsletterIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiDownloadPdfRoute: ApiDownloadPdfRoute,
  ApiPublicChatRoute: ApiPublicChatRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicNewsletterRoute: ApiPublicNewsletterRoute,
  ApiPublicTrackVisitRoute: ApiPublicTrackVisitRoute,
  ApiPublicTtsRoute: ApiPublicTtsRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicCronMonthlyNewsletterRoute: ApiPublicCronMonthlyNewsletterRoute,
  ApiPublicCronNewsletterSchedulerRoute: ApiPublicCronNewsletterSchedulerRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
